### ISSUE TITLE
add market value history for players

### ISSUE THREAD

**Issue by BenoitLondon** [dcaribou/transfermarkt-datasets#70]
Hi currently the current market value column in players dataset is mostly empty.
Could we have an updated value there and if possible the history of values in another table maybe like `values` ?
Thank you for sharing all this!

**Comment by dcaribou** [comment]
Hi @BenoitLondon, thanks for raining this issue!

On the blanks in `market_value_in_gbp`, I think this may have been caused by an upstream html change on Transfermarkt side. I'll have a look, it shouldn't be difficult to fix as long as the value is actually there somewhere in the player page.

Market history is more tricky to scrape, but definitely possible I think. Checkout [this](https://github.com/dcaribou/transfermarkt-scraper/issues/37) issue in the scraper project.

**Comment by dcaribou** [comment]
Historical market values for players are now available in the new `player_valuations` file.
